[0;1;31m‚óè[0m gunicorn.service - gunicorn daemon
     Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; vendor preset: enabled)
     Active: [0;1;31mfailed[0m (Result: exit-code) since Sat 2022-12-03 09:53:19 UTC; 28s ago
TriggeredBy: [0;1;31m‚óè[0m gunicorn.socket
    Process: 71830 ExecStart=/home/ubuntu/Fullstack-Hackaton/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock config.wsgi:application [0;1;31m(code=exited, status=1/FAILURE)[0m
   Main PID: 71830 (code=exited, status=1/FAILURE)

Dec 03 09:53:19 ip-172-26-3-206 gunicorn[71830]:   File "/home/ubuntu/Fullstack-Hackaton/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
Dec 03 09:53:19 ip-172-26-3-206 gunicorn[71830]:     self.reap_workers()
Dec 03 09:53:19 ip-172-26-3-206 gunicorn[71830]:   File "/home/ubuntu/Fullstack-Hackaton/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
Dec 03 09:53:19 ip-172-26-3-206 gunicorn[71830]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Dec 03 09:53:19 ip-172-26-3-206 gunicorn[71830]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Dec 03 09:53:19 ip-172-26-3-206 systemd[1]: [0;1;39m[0;1;31m[0;1;39mgunicorn.service: Main process exited, code=exited, status=1/FAILURE[0m
Dec 03 09:53:19 ip-172-26-3-206 systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mgunicorn.service: Failed with result 'exit-code'.[0m
Dec 03 09:53:19 ip-172-26-3-206 systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mgunicorn.service: Start request repeated too quickly.[0m
Dec 03 09:53:19 ip-172-26-3-206 systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mgunicorn.service: Failed with result 'exit-code'.[0m
Dec 03 09:53:19 ip-172-26-3-206 systemd[1]: [0;1;31m[0;1;39m[0;1;31mFailed to start gunicorn daemon.[0m
